import Foundation
import PasteCore

public protocol ClipboardPayloadSource: AnyObject {
    func currentChangeCount() -> Int
    func currentPayloads() -> [ClipboardPayload]
    func sourceApplication() -> (name: String?, bundleID: String?)
}

public extension ClipboardPayloadSource {
    func sourceApplication() -> (name: String?, bundleID: String?) { (nil, nil) }
}

public final class ClipboardMonitor: NSObject, ClipboardMonitoring {
    private let source: ClipboardPayloadSource
    private let classifier: ClipboardClassifying
    private let historyStore: ClipboardHistoryProviding
    private let interval: TimeInterval
    private let newItemHandler: (ClipboardItem) -> Void
    private var lastChangeCount: Int
    private var timer: Timer?
    private var pendingSelfWriteSignature: String?
    public var settingsProvider: () -> ClipboardLibrarySettings = { ClipboardLibrarySettings() }
    public var isPaused = false {
        didSet { lastChangeCount = source.currentChangeCount(); pendingSelfWriteSignature = nil }
    }
    public func resetBaseline() { lastChangeCount = source.currentChangeCount(); pendingSelfWriteSignature = nil }

    public init(
        source: ClipboardPayloadSource,
        classifier: ClipboardClassifying,
        historyStore: ClipboardHistoryProviding,
        interval: TimeInterval = 0.5,
        newItemHandler: @escaping (ClipboardItem) -> Void = { _ in }
    ) {
        self.source = source
        self.classifier = classifier
        self.historyStore = historyStore
        self.interval = interval
        self.newItemHandler = newItemHandler
        self.lastChangeCount = source.currentChangeCount()
        super.init()
    }

    public convenience init(
        classifier: ClipboardClassifying,
        historyStore: ClipboardHistoryProviding,
        interval: TimeInterval = 0.5,
        newItemHandler: @escaping (ClipboardItem) -> Void = { _ in }
    ) {
        self.init(
            source: SystemClipboardPayloadSource(),
            classifier: classifier,
            historyStore: historyStore,
            interval: interval,
            newItemHandler: newItemHandler
        )
    }

    public func start() {
        guard timer == nil else { return }

        timer = Timer.scheduledTimer(
            timeInterval: interval,
            target: self,
            selector: #selector(timerFired),
            userInfo: nil,
            repeats: true
        )
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    public func markSelfWrite(signature: String) {
        pendingSelfWriteSignature = signature
    }

    public func cancelSelfWrite(signature: String) {
        guard pendingSelfWriteSignature == signature else { return }
        pendingSelfWriteSignature = nil
    }

    public func poll(createdAt: Date = Date()) {
        let changeCount = source.currentChangeCount()
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount

        let settings = settingsProvider()
        guard !isPaused && !settings.capturePaused else { pendingSelfWriteSignature = nil; return }
        let app = source.sourceApplication()
        guard !settings.excludedBundleIDs.contains(app.bundleID ?? "") else { pendingSelfWriteSignature = nil; return }
        let payloads = source.currentPayloads()
        let privateTypes: Set<String> = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"]
        guard !(settings.ignoreConfidential && payloads.contains { privateTypes.contains($0.typeIdentifier) }),
              payloads.reduce(0, { $0 + $1.data.count }) <= 50 * 1024 * 1024 else { pendingSelfWriteSignature = nil; return }
        guard var item = classifier.makeItem(from: payloads, createdAt: createdAt) else {
            return
        }

        if let pendingSelfWriteSignature {
            self.pendingSelfWriteSignature = nil
            guard item.signature != pendingSelfWriteSignature else {
                return
            }
        }

        item.sourceAppName = app.name
        item.sourceBundleID = app.bundleID
        historyStore.insert(item)
        newItemHandler(item)
    }

    @objc private func timerFired() {
        poll()
    }
}
